
######### Reading Data
######################


```{r}
library(MASS)
library(survival)
library(survminer)
library(kableExtra)
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
PICSURE_network_URL <- "URL"
resource_id <- "resource_id"
token_file <- "token.txt"
token <- scan(token_file, what = "character")
myconnection <- picsure::connect(url = PICSURE_network_URL, token = token)
resource <- hpds::get.resource(myconnection, resourceUUID = resource_id)
selected_vars <- list("var1", "var2", "var3")
query <- hpds::new.query(resource)
hpds::query.select.add(query, selected_vars)
raw_df <- hpds::query.run(query, result.type = "dataframe") %>% dplyr::as_tibble()
```


```{r, Data-Management}
data_management <- function(df) {
  df$treatment <- as.factor(df$treatment)
  df$treatment <- relevel(df$treatment, ref="placebo")
}
df <- data_management(raw_df)
```


```{r, Synthetic Data Generation} 
SAMPLE_SIZE <- 510

# Fake data generation
covariates <- list(
  treatment = factor(c("hxcl", "placebo")) %>% relevel(ref = "placebo"),
  age = sample(seq.int(18, 90), 20, replace=TRUE),
  sex = factor(c("male", "female")),
  covid_os_0 = factor(seq(1, 5), ordered = TRUE),
  sofa_0 = sample(seq.int(0, 24), 20, replace=TRUE),
  ari_duration = sample(seq.int(0, 10), 20, replace=TRUE)
)
outcomes <- list(
  covid_os_15 = factor(seq(1, 7), ordered = TRUE),
  covid_os_3 = factor(seq(1, 7), ordered = TRUE),
  covid_os_8 = factor(seq(1, 7), ordered = TRUE),
  covid_os_29 = factor(seq(1, 7), ordered = TRUE),
  time_to_death_or_discharged = seq(1, 29),
  time_to_recovery = seq(1, 29),
  death_14 = factor(c(TRUE, FALSE)),
  death_28 = factor(c(TRUE, FALSE)),
  discharge_28 = factor(c(TRUE, FALSE)),
  death_ecmo_28 = factor(c(TRUE, FALSE)),
  o2_free_28 = factor(c(TRUE, FALSE)),
  vent_free_28 = factor(c(TRUE, FALSE)),
  vaso_free_28 = factor(c(TRUE, FALSE)),
  icu_free_28 = factor(c(TRUE, FALSE)),
  hosp_free_28 = factor(c(TRUE, FALSE))
)
safety <- list(
  seizure = c(TRUE, FALSE),
  arrythmia = c(TRUE, FALSE),
  cardiac_arrest = c(TRUE, FALSE),
  asat_alat = c(TRUE, FALSE),
  pancreatitis = c(TRUE, FALSE),
  aki = c(TRUE, FALSE),
  dialysis = c(TRUE, FALSE),
  hypoglycemia = c(TRUE, FALSE),
  cytopenia = c(TRUE, FALSE),
  dermatologic = c(TRUE, FALSE)
) %>% lapply(factor)
variables <- c(covariates, outcomes, safety)
df <- lapply(variables, sample, size = SAMPLE_SIZE, replace = TRUE) %>% 
  as_tibble() 
df[["patient_id"]] <- 1:nrow(df)
```


```{r, Data Management}

df$death <- ifelse(df$covid_os_29 == 1, 1, 0)
df$discharged <- ifelse(df$covid_os_29 %in% c(6, 7), 1, 0)

```


```{r, OS figure}
os_df <- df %>% 
  mutate(across(starts_with("covid_os"), as.numeric)) %>% 
  pivot_longer(cols = starts_with("covid_os"),
               names_to = c("COVID_os", "date"),
               names_sep = "_(?=[0-9])", 
               values_to = "value") %>% 
  mutate(value = recode_factor(as.ordered(value),
                               "7" = "Discharged, no limitation in activity",
                               "6" = "Discharged, limitation in activity",
                               "5" = "Hospitalized without oxygen",
                               "4" = "Hospitalized with oxygen",
                               "3" = "Noninvasive ventilation or high-flow nasal cannula",
                               "2" = "Invasive mechanical ventilation or ECMO",
                               "1" = "Death")
  )

barplot_width = 0.4
plot <- os_df %>%
  filter(date %in% c("15", "29")) %>% 
  ggplot(aes(x = date, fill = value)) +
  geom_bar(width = barplot_width) +
  facet_grid( ~ treatment) + 
  scale_fill_brewer(palette = "Greens") +
  theme_bw() +
  theme(panel.margin = grid::unit(c(0), "lines"))

str(plot)

pg <- ggplot_build(plot)

str(pg)
data_plot <- pg[[1]][[1]]

y_position <- pivot_wider(data_plot, 
              id_cols = c(fill, PANEL),
              values_from = y,
              names_from = x) %>% 
  rename(y_left = "1", y_right = "2")
x_position <- pivot_wider(data_plot,
                          id_cols = c("fill", "PANEL"),
                          names_from = c("x"), 
                          values_from = c("xmax", "xmin")) %>% 
  rename(x_left = xmax_1, x_right = xmin_2) %>% 
  dplyr::select(-c(xmax_2, xmin_1))

line_df <- inner_join(y_position, x_position)

ggplot(line_df) + 
  
plot +
  geom_segment(aes(x = x_left, xend = x_right, y = y_left, yend = y_right),
               data = line_df) 


str(data_plot)
```

# Outcome Analysis

```{r}


result_polr <- function(formula, df) {
  fitted_model <- MASS::polr(formula, Hess = TRUE, dat = df)
  coef_table <- coef(summary(fitted_model))
  OR <- exp(coef(fitted_model))
  coeff_names <- names(OR)
  ci <- confint(fitted_model)[coeff_names,]
  p <- pnorm(abs(coef_table[coeff_names, "t value"]), lower.tail = FALSE) * 2
  cbind("OR" = OR, ci, "p" = p)
}
```


```{r, Primary Outcome}
primary_outcome_name <- "covid_os_15"
formula_primary <- paste(primary_outcome_name,
                         paste(names(covariates), collapse = " + "), 
                         sep = " ~ ")
primary_outcome_result <- result_polr(formula_primary, df)
row.names(primary_outcome_result) <- recode(row.names(primary_outcome_result),
       "treatmenthxcl" = "Hydroxychloroquine",
       "age" = "Age",
       "sexmale" = "Gender (male)",
       "covid_os_0.L" = "COSC (L)",
       "covid_os_0.Q" = "COSC (Q)",
       "covid_os_0.C" = "COSC (C)",
       "covid_os_0^4" = "COSC (^4)",
       "sofa_0" = "SOFA Score",
       "ari_duration" = "ARI offset")
kableExtra::kable(primary_outcome_result, 
                  caption = "Primary Outcome Analysis: Odds Proportional Regression Model on COSC at 14 days") %>% kable_minimal()

```

```{r}
# Secondary outcomes
secondary_outcomes_ordered <- c(
  "covid_os_3",
  "covid_os_8",
  "covid_os_29"
)

list_result_secondary_outcome <- list()


for (secondary_outcome_name in secondary_outcomes_ordered) {
  formula_secondary <- paste(secondary_outcome_name,
                              paste(names(covariates), collapse = " + "),
                              sep = " ~ ")
  list_result_secondary_outcome[[secondary_outcome_name]] <- result_polr(formula_secondary, df)["treatmenthxcl",]
}


table_secondary_outcomes <- bind_rows(list_result_secondary_outcome, .id = "Number of Days After Randomization")
table_secondary_outcomes[["Number of Days After Randomization"]] <- recode(table_secondary_outcomes[["Number of Days After Randomization"]],
                                                                 "covid_os_3" = "3",
                                                                 "covid_os_8" = "8",
                                                                 "covid_os_29" = "29")
table_secondary_outcomes %>% 
  kable(caption="Effect of Hydroxychloroquine on COVID Outcomes Scale category") %>%
  kable_minimal()
```

```{r}
result_logistr <- function(formula, df) {
  fitted_model <- glm(formula, family = binomial(link = "logit"), data = df)
  coef_table <- coef(summary(fitted_model))
  OR <- exp(coef(fitted_model)) 
  ci <- confint(fitted_model)
  p <- coef_table[, "Pr(>|z|)"]
  cbind("OR" = OR, ci, "p" = p)
}

secondary_outcomes_binary <- c("death_14",
                               "death_28",
                               "discharge_28",
                               "death_ecmo_28",
                               "o2_free_28",
                               "vent_free_28",
                               "vaso_free_28",
                               "icu_free_28",
                               "hosp_free_28")
for (secondary_outcome_name in secondary_outcomes_binary) {
  formula_secondary <- paste(secondary_outcome_name,
                             "treatment",
                             sep = " ~ ")
  list_result_secondary_outcome[[secondary_outcome_name]] <- result_logistr(formula_secondary, df)
}


```

```{r, Survival Outcomes}
secondary_outcomes_survival <- "time_to_death"
secondary_outcomes_survival <- "time_to_discharge"

# Time to Death
coxph_death <- coxph(Surv(df$time_to_death_or_discharged, df$death) ~ treatment + age +
        sex + covid_os_0 +
        sofa_0 + ari_duration, 
      data = df)

survfit_death <- survfit(Surv(df$time_to_death_or_discharged, df$death) ~ treatment, 
      data = df)


# Time to discharge
df$death_discharge <- as.factor(ifelse(df$covid_os_29 < 6, 
                             ifelse(df$covid_os_29 != 1, 
                             "censor", "death"),
                             "discharge"))

discharge_data <- finegray(Surv(time_to_death_or_discharged, df$death_discharge) ~ .,
                           data=df,
                           etype="discharge")

discharge_survival <- coxph(Surv(fgstart, fgstop, fgstatus) ~ treatment + age +
        sex + covid_os_0 +
        sofa_0 + ari_duration, data=discharge_data,
      weight= fgwt)
survfit_discharge <- survfit(
Surv(df$time_to_death_or_discharged, df$discharged) ~ treatment, 
      data = df)


ggsurvplot(survfit_death,
             size = 1,                 # change line size
  palette = c("#E7B800", "#2E9FDF"),# custom color palettes
  conf.int = FALSE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =c("Hydroxychloroquine", "Placebo"),
  risk.table.height = 0.25,
  ggtheme = theme_bw(), 
  combine = TRUE, 
  keep_data = TRUE, 
  type="cuminc", 
  title = "Treatment Effect on Survival"
)
```

```{r}
ggsurvplot(survfit_discharge,
             size = 1,                 # change line size
  palette = c("#E7B800", "#2E9FDF"),# custom color palettes
  conf.int = FALSE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =c("Hydroxychloroquine", "Placebo"),
  risk.table.height = 0.25,
  ggtheme = theme_bw(), 
  combine = TRUE, 
  keep_data = TRUE, 
  type="cuminc", 
  title = "Treatment Effect on Time-to-Discharge"
)
# ggsurvplot(list(death = survfit_death, discharge = survfit_discharge), 
#              size = 1,                 # change line size
#   # palette =
#   #   c("#E7B800", "#2E9FDF", "#E7B800", "#2E9FDF"),# custom color palettes
#   conf.int = FALSE,          # Add confidence interval
#   pval = TRUE,              # Add p-value
#   risk.table = TRUE,        # Add risk table
#   risk.table.col = "strata",# Risk table color by groups
#   # legend.labs =
#   #   c("Hydroxychloroquine", "Placebo",
#   #        "Hydroxychloroquine", "Placebo"),    # Change legend labels
#   risk.table.height = 0.25, # Useful to change when you have multiple groups
#   ggtheme = theme_bw(), 
#   combine = TRUE, 
#   keep_data = TRUE, 
#   type="cuminc"# Change ggplot2 theme
# )

```



# Safety Outcomes

```{r}
list_result_safety_outcome <- list()
for (safety_outcome_name in names(safety)) {
  formula_safety <- paste(safety_outcome_name,
                             "treatment",
                             sep = " ~ ")
  list_result_safety_outcome[[safety_outcome_name]] <- result_logistr(formula_safety, df)
}

# Adverse Events table
# df[names(safety)] <- df[names(safety)] %>% lapply(as.logical.factor) %>% as_tibble()
adverse_event_table <- df %>% 
  group_by(treatment) %>% 
  dplyr::select(all_of(names(safety))) %>% 
  summarise_all(sum) %>% 
  pivot_longer(cols = all_of(names(safety)),
               names_to = "adverse_event",
              values_to = "count") %>% 
  pivot_wider(names_from = treatment, values_from = count) %>% 
  rename("Hydroxychloroquine" = "hxcl",
         "Placebo" = "placebo", 
         "Adverse Event" = "adverse_event")

kable(adverse_event_table, caption = "Safety Outcomes: Adverse Event Counts") %>% kable_minimal()


```

